# Setup
title:               Prayag Chatha
tagline:             Everything Flows
description:         μὴ εἶναι βασιλικὴν ἀτραπὸν ἐπί γεωμετρίαν
url:                 https://chathasphere.github.io/
baseurl:             ''
permalink:           pretty
# consider: permalink: /:categories/:title/

# About/contact
author:
  name:              Prayag George Singh Chatha
  email:             pchatha at umich dot edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
