# Setup
title:               Everything Flows
tagline:             Prayag Chatha's Webpage
description:         Welcome!
url:                 https://chathasphere.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Prayag Chatha
  url:               A specter is haunting bird app
  email:             pchatha at umich dot edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
